### ISSUE TITLE
cvpr2020

### ISSUE THREAD

**Issue by caiyuanhao1998** [HuangJunJie2017/UDP-Pose#1]
哥，能方便透露一下你们cvpr的初始得分吗？我在学习你们的paper。

**Comment by HuangJunJie2017** [comment]
@caiyuanhao1998  原始得分233😏 我也很好奇你们的rsn ，MegBrain已经开源了，啥时候放靠谱的代码（能复现论文指标的），pytorch的阉割版让人失望啊

**Comment by caiyuanhao1998** [comment]
谢谢~，megdl源码之后再说吧。现在我在忙着搞毕设呢。

**Comment by HuangJunJie2017** [comment]
看来是毕设要用到UDP了，加油~
