### ISSUE TITLE
Reproduce

### ISSUE THREAD

**Issue by stoa-xh91** [HuangJunJie2017/UDP-Pose#10]
Hi @HuangJunJie2017 , 

thanks for releasing code. I'm trying to use it to reproduce the results (UDP-HRNet-W32) reported in the paper. I used the trained model stored in BaiduDisk and tested it on COCO val2017 set. Here is the result  i obtained:

offset | 256x192 | w32 | | gt bbox   | 74.6
offset | 256x192 | w32 | | det bbox | 73.3

I wonder if it exists bugs or not ?

**Comment by HuangJunJie2017** [comment]
@stoa-xh91 you are the only one who report this problem, Your result is a bit lower than mine. Have you ever modify any code in this repo?

**Comment by stoa-xh91** [comment]
@HuangJunJie2017 No modifications. I've double-checked the usage of this code and re-test it, the result is still unchanged. I guess the provided model is not the one we want. Could you please re-test it for sure?

**Comment by HuangJunJie2017** [comment]
@stoa-xh91 i have checked before i release the code and pretrained models, and the others have no problem in reproducing the result i report. I check it again just now and the result is 78.0AP for gt bbox. I recommend you to reproduce the original hrnet(without udp) to see if the result is the same as xiaobin's

**Comment by stoa-xh91** [comment]
Hi @HuangJunJie2017 , I've found the problem. the version of transform_pred function in file "transforms.py" is old,  that used in original hrnet. I've changed it to the newest one, the result can be reproduced now. Thank you for replying and share this great work.
Thanks again.

**Comment by syusukee** [comment]
Hi, when you reproduce the results, have you met the situation that the AP is always nearly 0 during  training?  @stoa-xh91

**Comment by stoa-xh91** [comment]
No @syusukee 

> Hi, when you reproduce the results, have you met the situation that the AP is always nearly 0 during training? @stoa-xh91
