### ISSUE TITLE
does the repo contain the code for detecting the persons?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [HuangJunJie2017/UDP-Pose#11]
hi @HuangJunJie2017 
how do i get the human detector with the ap 65.1 as described in the readme?

**Comment by HuangJunJie2017** [comment]
@zimenglan-sysu-512  no, this repo doesn't provide the code for detecting the persons. If you want the human detection result, you can find it in 'Quick Start' section. And if you want the human detector, you can refer to mmdet for pretrained HTC models, as we use this repo/model to generate the human detection result.
