### ISSUE TITLE
keypoints shifted?

### ISSUE THREAD

**Issue by Tsings04** [HuangJunJie2017/UDP-Pose#12]
I have tested the hrnet-w32-256x192 with and without udp on coco valset. Your implementation achieved better score with 78% AP compared to the original one with 76.5% AP. However when i check the visualization result of the output, i found that the keypoints are not really accurate on the position. As shown in the screenshot, the left one is the output of your implementation, and the right one is from the original hrnet. Do you know the reason?

![Screenshot from 2020-09-25 11-58-38](https://user-images.githubusercontent.com/37935540/94225795-8e560c00-ff28-11ea-8b22-bb46ec67a726.png)

**Comment by HuangJunJie2017** [comment]
@Tsings04 emmm, it seem that all result from udp is biased. I suppose that the data processing pipeline in the original visualization demo is become biased in this repo. I have not  used or modify this demo and i will check its data processing pipeline in the next few days.

**Comment by Tsings04** [comment]
> @Tsings04 emmm, it seem that all result from udp is biased. I suppose that the data processing pipeline in the original visualization demo is become biased in this repo. I have not used or modify this demo and i will check its data processing pipeline in the next few days.

Thanks for your reply! It seems to be the case. I am looking forward to your visual jobs :)

**Comment by HuangJunJie2017** [comment]
@Tsings04 the bug has been fixed, and thanks for your question!

**Comment by Tsings04** [comment]
> @Tsings04 the bug has been fixed, and thanks for your question!

Thank you for your jobs! I have tested the visualization and now it performs so well. Nice to have this SOTA implementation :)
