### ISSUE TITLE
Hello, where is the PRM code in your RSN project

### ISSUE THREAD

**Issue by superWSL** [HuangJunJie2017/UDP-Pose#14]
Hello, where is the PRM code in your RSN project, i can not find that, is the code not published?

**Comment by HuangJunJie2017** [comment]
emmm, There is an official implement here: https://github.com/HuangJunJie2017/UDP-Pose/blob/master/RSN/exps/4XRSN18.coco/network.py
but this has not been use in this project~
you can refer to the original RSN project for more details or question this problem~ 
https://github.com/caiyuanhao1998/RSN
https://github.com/caiyuanhao1998/RSN/issues/5
