### ISSUE TITLE
How can i use my own custom dataset and obtain metrics?

### ISSUE THREAD

**Issue by kathanvyas** [HuangJunJie2017/UDP-Pose#16]
I have some 500 images and annotation json for those 500 files. I want to evaluate the model on this new test dataset and obtain AP, AP0.5 from that. How can I do that? I could change data dir to my new data directory. However what should I do about the person detection result of COCO val2017 as I do not have that for my dataset for now.

**Comment by HuangJunJie2017** [comment]
@kathanvyas  you need to prepared data in coco format~ 
you need to detect human first and save the human bounding boxes in coco format 'person_keypoints_val2017.json'
you can refer to mmdet for human detector

**Comment by kathanvyas** [comment]
Oh so we need to have the human bounding boxes detected prior to using this repo?

**Comment by HuangJunJie2017** [comment]
@kathanvyas yes, human bounding boxes is the precondition for top-down paradigm multi-instance human pose estimation
but for bottom-down paradigm, human bounding boxes is not necessary. you can refer to HigherHRNet in mmpose for bottom-up methods
