### ISSUE TITLE
May I ask questions related to the paper? 

### ISSUE THREAD

**Issue by ShuangjunLiu** [HuangJunJie2017/UDP-Pose#18]
In the paper, 3.1.1 
The way to transform output back to source is described as: 
![image](https://user-images.githubusercontent.com/19880963/100811957-e9651d00-3409-11eb-8e80-cd34f18d4d8b.png)
I have difficult to understand this explanation. 
I can't see there is a padding 1 operation to recover source coordinate in other works (which suppose to be biased)  

sec 3.1.2 
"Specifically, we adopt unit length as the image size measurement criterion,..." 
The unit length is "the distance between two adjacent pixels". 
Pixel suppose to be squared and the distance between pixels suppose to be equal to pixel size.  
What is the different between using  "distance"  or "pixel" to measure.  
I have difficulties to understand this concept.  

If this paper related question is not proper for git issues here, may I send you separate email for these issues?   
Thanks.

**Comment by HuangJunJie2017** [comment]
Q1 try to draw figure2 on your own, and if you can darw it by your self, you will find this relation of equivalence
Q2 study this in opposite aspect? i.e. considering the discrete image matrix as the sample point of the integer position in the continuous space O-XY~
