### ISSUE TITLE
paper中公式的一些疑问

### ISSUE THREAD

**Issue by PhoenixTree93** [HuangJunJie2017/UDP-Pose#20]
![image](https://user-images.githubusercontent.com/38270531/101439311-39cf0400-394f-11eb-9890-9b5c88c05aa5.png)
公式36中第三行两个flip相乘的结果为什么会多除一个Pwi，这里比较困惑

**Comment by HuangJunJie2017** [comment]
@PhoenixTree93 the explanation in cvpr paper is quite confused and now i am trying to fix this and preparing another version, which will be release next month(may be longer), if you are  urgent for this, contact me through email please~ junjie.huang@ieee.org

**Comment by PhoenixTree93** [comment]
ok, thanks!
