### ISSUE TITLE
where is the bottom-up version?

### ISSUE THREAD

**Issue by chen1mingCuc** [HuangJunJie2017/UDP-Pose#21]
Hi, can you show me the path to *higherHRNet + udp* codes? i can't find them (ノへ￣)
And how did you make the tradeoff in bottom-up methods, will there be a paper or blog to explain it?

**Comment by HuangJunJie2017** [comment]
thanks for your attention!
the code have been public available in this branch of mmpose https://github.com/HuangJunJie2017/CrownPose 
i am preparing a new version of the paper to include the study of udp problem in bottom-up method HigherHRNet and will release it in next month or may be more latter, if you are urgent about this, contact me through email, i will send you a draft. junjie.huang@ieee.org
