### ISSUE TITLE
there is no w32_256x256_adam_lr1e-3.yaml 

### ISSUE THREAD

**Issue by azuryl** [HuangJunJie2017/UDP-Pose#22]
I run 
python tools/test.py \
    --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \
    TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth \
    TEST.USE_GT_BBOX Fals
from https://github.com/HuangJunJie2017/UDP-Pose/tree/master/deep-high-resolution-net.pytorch

but in experiments/coco/hrnet/  just have w32_256x192_adam_lr1e-3_offset_ofm.yaml and does not match  pose_hrnet_w32_256x192.pth 
https://github.com/HuangJunJie2017/UDP-Pose/tree/master/deep-high-resolution-net.pytorch/experiments/coco/hrnet

and how to run your UDP-hrnet_w32_256x192

**Comment by HuangJunJie2017** [comment]
where did you down load the model~ we provide the models trained with udp here 
![image](https://user-images.githubusercontent.com/31001081/101586029-fd1d0e80-3a1b-11eb-9fa8-ad0b78db4b4f.png)

**Comment by azuryl** [comment]
I  had download your model and updated the w32_256x192_adam_lr1e-3.yaml  from Hrnet 
but there is error
python inference.py --cfg ../experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml  --videoFile ../../../Alexander\ Zverev\ vs\ Dominic\ Thiem\ -\ US\ Open\ 2020\ Final.mp4  --writeBoxFrames --outputDir output TEST.MODEL_FILE UDP-hrnet_w32_256x192.pth 
=> loading model from UDP-hrnet_w32_256x192.pth
Traceback (most recent call last):
  File "inference.py", line 341, in <module>
    main()
  File "inference.py", line 226, in main
    pose_model.load_state_dict(torch.load(cfg.TEST.MODEL_FILE), strict=False)
  File "/home/azuryl/anaconda3/envs/udppose/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PoseHighResolutionNet:
	size mismatch for final_layer.weight: copying a param with shape torch.Size([51, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([17, 128, 1, 1]).
	size mismatch for final_layer.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([17]).

**Comment by HuangJunJie2017** [comment]
can you run the origin hrnet repo with the pretrained models provided by the origin hrnet repo?

**Comment by HuangJunJie2017** [comment]
If you can't, you should question on the origin hrnet repo for support. 
If you can, you won't have problem in using this repo with the pretrained models provided in this repo.

**Comment by HuangJunJie2017** [comment]
try not to use the origin hrnet repo alone with the pretrained models in this repo, so do the inverse

**Comment by azuryl** [comment]
I had run in orgin repo

your repo should  use https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml
should not use  w32_256x192_adam_lr1e-3_offset_ofm.yaml

**Comment by HuangJunJie2017** [comment]
emmm, but the others have no problem about using this. 

make sure that you use this config: experiments/coco/hrnet/w32_256x192_adam_lr1e-3_offset_ofm.yaml
make sure that you use this checkpoint: UDP-hrnet_w32_256x192.pth  which should be downloaded from here: https://pan.baidu.com/s/1mPuVj8piYzgWjoRgyd0Cwg     (dsa9)

run this under https://github.com/HuangJunJie2017/UDP-Pose/tree/master/deep-high-resolution-net.pytorch ?

python tools/test.py  --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3_offset_ofm.yaml TEST.MODEL_FILE models/pytorch/pose_coco/UDP-hrnet_w32_256x192.pth TEST.USE_GT_BBOX False

**Comment by azuryl** [comment]
"emmm, but the others have no problem about using this."
since your hrnet fold's name is same as orginal repo but in fact your hrnet's fold  just can run your model but orginal model .I had run youe model success
![udphrnet](https://user-images.githubusercontent.com/23340671/102123814-6a161700-3e15-11eb-912a-1edb707a7318.png)
