### ISSUE TITLE
missing keypoint-aware occlusion augmentation

### ISSUE THREAD

**Issue by AndersonZhangyq** [HuangJunJie2017/UDP-Pose#25]
In the [v1](https://arxiv.org/pdf/2008.07139v1.pdf), a keypoint-aware occlusion augmentation(shorten as `OA` in the following) is proposed, while in the [v2](https://arxiv.org/pdf/2008.07139.pdf), there is no place for that. But when I compare table 1 in v1 and the table 2 in v2, the result is consistent.
After reading the source code of AID in mmpose pull request, I failed to find anything related to OA.
Why do you drop OA? Does that indicate that using `CutOut` and `HaS` can get the same result as `OA` does?

**Comment by HuangJunJie2017** [comment]
@AndersonZhangyq yes，ablation study is absent in v1, and further experiment shows that “keypoint-aware” is not necessary, so we remove it
