### ISSUE TITLE
Question about the pre-process

### ISSUE THREAD

**Issue by AndersonZhangyq** [HuangJunJie2017/UDP-Pose#26]
In [_xywh2cs(self, x, y, w, h)](https://github.com/HuangJunJie2017/UDP-Pose/blob/d742edd0142b87886d287e56315328f9639d508c/deep-high-resolution-net.pytorch/lib/dataset/coco.py#L214), to get the scale, the bounding box is rescaled to match the aspect ratio of the model input.

From the source code, I think the standard workflow is to rescale the bounding box **and then** crop the image according to the rescaled bounding box, which is inconsistent with the standard workflow mentioned in paper(which is to rescale the **cropped** image).
And I found this behavior in mmpose, which seems to be a common behavior.

Is there any special reason to do so? In my point of view, this behavior may includes much more context then expected.
Or the input aspect ratio chosen is designed for COCO, based on the statistics of aspect ratio of person bounding boxes?

**Comment by HuangJunJie2017** [comment]
this function is inherited from the orginal hrnet without modification for fair comparison~

**Comment by AndersonZhangyq** [comment]
Fair enough
