### ISSUE TITLE
why preds need X scale

### ISSUE THREAD

**Issue by azuryl** [HuangJunJie2017/UDP-Pose#28]
https://github.com/HuangJunJie2017/UDP-Pose/blob/d742edd0142b87886d287e56315328f9639d508c/deep-high-resolution-net.pytorch/lib/utils/transforms.py#L67
def transform_preds(coords, center, scale, output_size):
    scale = scale * 200.0
    scale_x = scale[0]/(output_size[0]-1.0)
    scale_y = scale[1]/(output_size[1]-1.0)
    target_coords = np.zeros(coords.shape)
    target_coords[:,0] = coords[:,0]*scale_x + center[0]-scale[0]*0.5
    target_coords[:,1] = coords[:,1]*scale_y + center[1]-scale[1]*0.5
    return target_coords

**Comment by HuangJunJie2017** [comment]
please refer to our paper in https://arxiv.org/abs/1911.07524
