### ISSUE TITLE
why  need norm = np.ones((pred.shape[0], 2)) * np.array([h, w]) / 10 in accuracy

### ISSUE THREAD

**Issue by azuryl** [HuangJunJie2017/UDP-Pose#29]
Dear JunJie

in https://github.com/HuangJunJie2017/UDP-Pose/blob/d742edd0142b87886d287e56315328f9639d508c/deep-high-resolution-net.pytorch/lib/core/evaluate.py#L55
 norm = np.ones((pred.shape[0], 2)) * np.array([h, w]) / 10
I did know why use norm and why need /10
and in https://github.com/HuangJunJie2017/UDP-Pose/blob/d742edd0142b87886d287e56315328f9639d508c/deep-high-resolution-net.pytorch/lib/core/evaluate.py#L16
and why
                normed_preds = preds[n, c, :] / normalize[n]
                normed_targets = target[n, c, :] / normalize[n]

when I print the output   preds[n, c, :]  and  target[n, c, :] are  very different  such as[ 27,30] and [4,8] 

Thank you

**Comment by HuangJunJie2017** [comment]
@azuryl emm, i think the accuracy is meaningless. So i haven't paid attention on this function. You can question this in the origin hrnet repo.

**Comment by azuryl** [comment]
Dear JunJie thank your reply

 in
https://github.com/HuangJunJie2017/UDP-Pose/blob/d742edd0142b87886d287e56315328f9639d508c/deep-high-resolution-net.pytorch/lib/core/function.py#L185 

lif config.MODEL.TARGET_TYPE == 'offset':
                _, avg_acc, cnt, pred = accuracy(output.cpu().numpy()[:, ::3, :, :],
                                                 target.cpu().numpy()[:, ::3,:, :])
you used this function. I do not know why

Thank you

**Comment by HuangJunJie2017** [comment]
@azuryl i just imitate the source hrnet repo to add this for preventing the error.

**Comment by azuryl** [comment]
ok I see thank :)
