### ISSUE TITLE
why  your json's bboxes have so many no human's joints

### ISSUE THREAD

**Issue by azuryl** [HuangJunJie2017/UDP-Pose#30]
Dear JunJie

I am wondering in  multi_scales_val_msra.json have 87481 boxes and many of  joints are  not human's joints such as cat or  elephant's joints . but if I use GT's box it just have 6000+ around boxes and these joints are full human's joints . and I found   "joints_vis" all set 1.  I am very confused. can you tell me the reason.

thank you

**Comment by HuangJunJie2017** [comment]
@azuryl multi_scales_val_msra.json is result from HTC detector. The boxes without human instance in your eyes, would be considered as human instance in detection task.  These boxes always have a low confidence. The concept of confidence in detection is important, and you can refer to some papers in detection aspect for more details like faster-rcnn.
