### ISSUE TITLE
Confuse about merge origin hrnet into mmpose

### ISSUE THREAD

**Issue by Huuush** [HuangJunJie2017/UDP-Pose#31]
Sry to bother. I use UDP for cloth landmark detection, and I implement it in your origin repo. But when I try to merge it in to mmpose, the mAP is not nomal when compare with origin implementation. Do you have any advice ? I'm new to mmpose.( I implement my dataset by inheriting the 'Topdowndataset' instead of origin Jointdataset.) Two more questions:  
1.Btw, I notice that the implementation of the hyperparameter: **KPD** is different between origin and mmpose. In mmpose, we must calculate it by: `valid_radius = factor * heatmap_size[1]`, so does it mean that i must change the factor if I got a different heatmap_size?   
2.I wonder if I need to change the **KPD** for my own dataset? KPD=3.5 is just suitable for human pose?
Thanks a lot !!!  :)

**Comment by HuangJunJie2017** [comment]
'the mAP is not normal' to what extent?

**Comment by HuangJunJie2017** [comment]
as far as i know , kpd should be  adjusted when the heatmap size is changed (a linear dependence).

**Comment by Huuush** [comment]
> 'the mAP is not normal' to what extent?
the origin is 0.688 and the mmpose implementation is 0.652

**Comment by Huuush** [comment]
the origin is 0.688 and the mmpose implementation is 0.652

**Comment by HuangJunJie2017** [comment]
you can try  heatmap only supervision in mmpose, both combined target and gaussian heatmap only target are provided in mmpose

**Comment by Huuush** [comment]
> as far as i know , kpd should be adjusted when the heatmap size is changed (a linear dependence).

I notice that the kpd is set to 5.25 for 384*288. How about 384*512? (嗐，谁让图给得越大 效果越好呢）

**Comment by Huuush** [comment]
> as far as i know , kpd should be adjusted when the heatmap size is changed (a linear dependence).

I notice that the kpd is set to 5.25 for 384x288. How about 384x512? (嗐，谁让图给得越大 效果越好呢）

**Comment by HuangJunJie2017** [comment]
emmm, the difference is not that large. You can convert the trained models into mmpose format, (adjust the keyname of parameters) to check the inference at first.

**Comment by HuangJunJie2017** [comment]
> > as far as i know , kpd should be adjusted when the heatmap size is changed (a linear dependence).
> 
> I notice that the kpd is set to 5.25 for 384x288. How about 384x512? (嗐，谁让图给得越大 效果越好呢）

kpd is set to 3.5 for 384x512 cloth landmark detection in original hrnet repo?

**Comment by Huuush** [comment]
> > > as far as i know , kpd should be adjusted when the heatmap size is changed (a linear dependence).
> > 
> > 
> > I notice that the kpd is set to 5.25 for 384x288. How about 384x512? (嗐，谁让图给得越大 效果越好呢）
> 
> kpd is set to 3.5 for 384x512 cloth landmark detection in original hrnet repo?

yep. hhhhhh maybe I need to read the UDP for anther time.

**Comment by Huuush** [comment]
> > > as far as i know , kpd should be adjusted when the heatmap size is changed (a linear dependence).
> > 
> > 
> > I notice that the kpd is set to 5.25 for 384x288. How about 384x512? (嗐，谁让图给得越大 效果越好呢）
> 
> kpd is set to 3.5 for 384x512 cloth landmark detection in original hrnet repo?

When the first time I introduce UDP to my own cloth landmark detection task, I set kpd to 3.5 acrroding to the readme, and now I know how to deal with it. Thanks for your wonderful work ! And thanks for your reply!!!

**Comment by Huuush** [comment]
Did you mind to tell me the result about UDP in RSN? Curious about it.
