### ISSUE TITLE
About KPD

### ISSUE THREAD

**Issue by MaxChu719** [HuangJunJie2017/UDP-Pose#33]
In the offset model, KPD should be the hyperparameter that controls the radius of the region of interest around the ground truth location. But in the implementation, it also controls the slope (and intercept) of the two offset heatmaps (seel below code):
```
elif self.target_type == 'offset':
            # self.heatmap_size: [48,64] [w,h]
            target = np.zeros((self.num_joints,
                               3,
                               self.heatmap_size[1]*
                               self.heatmap_size[0]),
                              dtype=np.float32)
            feat_width = self.heatmap_size[0]
            feat_height = self.heatmap_size[1]
            feat_x_int = np.arange(0, feat_width)
            feat_y_int = np.arange(0, feat_height)
            feat_x_int, feat_y_int = np.meshgrid(feat_x_int, feat_y_int)
            feat_x_int = feat_x_int.reshape((-1,))
            feat_y_int = feat_y_int.reshape((-1,))
            kps_pos_distance_x = self.kpd
            kps_pos_distance_y = self.kpd
            feat_stride = (self.image_size - 1.0) / (self.heatmap_size - 1.0)
            for joint_id in range(self.num_joints):
                mu_x = joints[joint_id][0] / feat_stride[0]
                mu_y = joints[joint_id][1] / feat_stride[1]
                # Check that any part of the gaussian is in-bounds

                x_offset = (mu_x - feat_x_int) / kps_pos_distance_x
                y_offset = (mu_y - feat_y_int) / kps_pos_distance_y

                dis = x_offset ** 2 + y_offset ** 2
                keep_pos = np.where((dis <= 1) & (dis >= 0))[0]
                v = target_weight[joint_id]
                if v > 0.5:
                    target[joint_id, 0, keep_pos] = 1
                    target[joint_id, 1, keep_pos] = x_offset[keep_pos]
                    target[joint_id, 2, keep_pos] = y_offset[keep_pos]
            target=target.reshape((self.num_joints*3,self.heatmap_size[1],self.heatmap_size[0]))
```

Is there any reason why you do that? It seems to be another "devil in the detail" worth studying...:)

**Comment by HuangJunJie2017** [comment]
@MaxChu719 Please refer to the latest verson of UDP in arxiv for the explaination of this setting.  https://arxiv.org/pdf/1911.07524.pdf

**Comment by MaxChu719** [comment]
@HuangJunJie2017 I have read through the paper and the only place i found about KPD is in section 3.2.2 (Combined classification and regression format), where it sais "...r is a hyperparameter referring the radius of the area classified as positive...". But the KPD in the implementation, as i understand, not only define the radius of interest of the offset but also it scale down the magnitude of the offset. So, KPD also served as the inverse weight of the offset loss. Am i misundersand something here?

**Comment by HuangJunJie2017** [comment]
@MaxChu719

>but also it scale down the magnitude of the offset. 

Well, this is another question
The initial purpose of scaling down the magnitude of the offset is just empirically making the offset to distribute within interval [0,1). It indeed scales down the offset loss in practice and, as i guess, should affect the final performance. 
Anyway, the implement of this paradigm is not the main concern in this paper, as far as it is unbiased. Some details are not considered thoroughly.

**Comment by MaxChu719** [comment]
@HuangJunJie2017 Thanks for the quick reply. I see your point that it is to normalize the offset interval to [0, 1). But you can also interpret it as the weight of the (unnormalized) offset loss. The reason why KDP has a pretty significant result is quite surprising. Maybe it is just a hyperparameter that happens to be quite good for COCO dataset. Anyway, thanks for the explanation and your good work.

**Comment by MaxChu719** [comment]
@HuangJunJie2017 Btw, in my original,  question i said "But in the implementation, it also controls the slope (and intercept) of the two offset heatmaps (seel below code)", i admit that i am not saying in very clear. It actually just mean that you also scale the offset loss...
