### ISSUE TITLE
Good job，but a little flaw？

### ISSUE THREAD

**Issue by igodogi** [HuangJunJie2017/UDP-Pose#34]
In “**_Results on COCO val2017 with detector having human AP of 65.1 on COCO val2017 dataset_**”： you give the _hrnet_ results just like the original paper rather than the results tested by the same detector of UDP（AP 65.1）? Emma... I am happy to know will the HRNet be better than UDP? Or, what is it that causes the unsatisfactory result of UDP when tested on coco_dev?
_**Your results:**_
![image](https://user-images.githubusercontent.com/26406574/121211072-c599fc80-c8ae-11eb-85bd-01690668a37f.png)

**_HRNet results with AP609 person detector:_**
![image](https://user-images.githubusercontent.com/26406574/121211128-d0ed2800-c8ae-11eb-8d68-7dbcf2527a02.png)

**Comment by HuangJunJie2017** [comment]
@igodogi 
We did the ablation study in coco-val to show the superiority of UDP over the original HRNet, where we use the same detection result (65.1 AP) for fair comparison. In COCO keypoint  test-dev, keypoint results with 65.1 AP detector (ours) have around 0.3\~0.4 AP superiority on the counterparts with 60.9 AP detector (original hrnet's). So the comparison in test-dev is not fair. It is just for showcasing the sota performance~
