### ISSUE TITLE
can't Makefile

### ISSUE THREAD

**Issue by DonaldKam** [HuangJunJie2017/UDP-Pose#4]
At the first step Makefile, it raises :EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path
Could you plz tell me the solution?

**Comment by HuangJunJie2017** [comment]
@DonaldKam which repo do you use? rsn or hrnet

**Comment by DonaldKam** [comment]
hrnet.
The detailed errors are below:
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by HuangJunJie2017** [comment]
@DonaldKam  It seem that the program can not find the rootpath of cuda , have you install it?  or make it available.? use command like 'nvcc --version'/'nvidia-smi' to check whether cuda is available, here is an example:
'''
[************* ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
'''

**Comment by DonaldKam** [comment]
Thank you and the compiling has been successful. But another problem arises:  File "/media/UDP/hrnet/tools/../lib/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'nms.cpu_nms'
I modified cpu_nms.pyx to cpu_nms.py. 
Then I got sucked in:
  File "/media/UDP/hrnet/tools/../lib/nms/cpu_nms.py", line 12
    cimport numpy as np
                ^
SyntaxError: invalid syntax

**Comment by HuangJunJie2017** [comment]
@DonaldKam  well, as far as i know, if you can make successfully, no error will be reported when you use this repo. 
make clean first?
 i mean when you run into mistake during 'make', make clean before  make again
nms is not necessary for keypoints detection ,you can comment out all code with this

**Comment by DonaldKam** [comment]
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_35'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 25 registers, 1280 bytes smem, 344 bytes cmem[0], 8 bytes cmem[2]
gcc -pthread -B /home/.conda/envs/upd/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/.conda/envs/upd/lib/python3.6/site-packages/numpy/core/include -I/usr/include -I/home/.conda/envs/upd/include/python3.6m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.6/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/.conda/envs/upd/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/.conda/envs/upd/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/.conda/envs/upd/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:581:
/home/.conda/envs/upd/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/.conda/envs/upd/compiler_compat -L/home/.conda/envs/upd/lib -Wl,-rpath=/home/.conda/envs/upd/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/nms_kernel.o build/temp.linux-x86_64-3.6/gpu_nms.o -L/usr/lib -Wl,-R/usr/lib -lcudart -o /media/INSTALL/UDP/hrnet/lib/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so

It seems the makefile compiling ran into mistake with numpy and i failed in the compiling. If nms is not necessary, why is it in the codes? Will that has no impact on the performance if i comment out all code with it?

**Comment by HuangJunJie2017** [comment]
@DonaldKam i am sure that the nms have not been used anywhere in this repo, i fork the original hrnet where nms is included. you can question the original hrnet for why~

**Comment by DonaldKam** [comment]
Thx for your patience and restarting the system solved all problem. Now it‘s working.

**Comment by HuangJunJie2017** [comment]
You're welcome
