### ISSUE TITLE
Difference between checkpoint.pth and model_best.pth

### ISSUE THREAD

**Issue by DonaldKam** [HuangJunJie2017/UDP-Pose#7]
When I was training the network, **checkpoint.pth** and **model_best.pth**  were saved? What's the difference between them? Why is the former larger?

**Comment by HuangJunJie2017** [comment]
@DonaldKam emm，you'd better pay more time on viewing the code~

'''def save_checkpoint(states, is_best, output_dir,
                    filename='checkpoint.pth'):
    torch.save(states, os.path.join(output_dir, filename))
    if is_best and 'state_dict' in states:
        torch.save(states['best_state_dict'],
                   os.path.join(output_dir, 'model_best.pth'))'''

**Comment by WangChen100** [comment]
> When I was training the network, **checkpoint.pth** and **model_best.pth** were saved? What's the difference between them? Why is the former larger?

model_best.pth includes the parameters of a single model which achieves best performance.

checkpoint.pth includes not only the parameters of model but also the parameters of optimizer.
