### ISSUE TITLE
Is it for single person pose estimation

### ISSUE THREAD

**Issue by DonaldKam** [HuangJunJie2017/UDP-Pose#8]
I tested on the 2958 samples and got the predicted results in single person. Isn't it for multi-person or single?
![image](https://user-images.githubusercontent.com/44252954/89706283-c4e6c000-d996-11ea-8c8c-952e6faaa642.png)

**Comment by DonaldKam** [comment]
def box_to_center_scale(box, model_image_width, model_image_height):
    """convert a box to center,scale information required for pose transformation
    Parameters
    ----------
    box : list of tuple
        list of length 2 with two tuples of floats representing
        bottom left and top right corner of a box
    model_image_width : int
    model_image_height : int
    Returns
    -------
    (numpy array, numpy array)
        Two numpy arrays, coordinates for the center of the box and the scale of the box
    """
    center = np.zeros((2), dtype=np.float32)

    bottom_left_corner = box[0]
    top_right_corner = box[1]
    box_width = top_right_corner[0]-bottom_left_corner[0]
    box_height = top_right_corner[1]-bottom_left_corner[1]
    bottom_left_x = bottom_left_corner[0]
    bottom_left_y = bottom_left_corner[1]
    center[0] = bottom_left_x + box_width * 0.5
    center[1] = bottom_left_y + box_height * 0.5

    aspect_ratio = model_image_width * 1.0 / model_image_height
    pixel_std = 200

Why is center[1] not like this : center[1] = bottom_left_y **-** box_height * 0.5？
Why is pixel_std  200？

**Comment by DonaldKam** [comment]
@HuangJunJie2017 
Looking forward to your answer

**Comment by HuangJunJie2017** [comment]
@DonaldKam I was busy with coco challenge last week,,  emmm, pixel_std is use for human bounding box scale normalization, this is not necessary, but the original hrnet use this without any explanation

**Comment by DonaldKam** [comment]
@HuangJunJie2017 Thank you. Why is scale 2-tuple since it is a single value in annot\train.json？How is it computed?

**Comment by HuangJunJie2017** [comment]
@DonaldKam  please refer to https://github.com/HuangJunJie2017/UDP-Pose/blob/master/deep-high-resolution-net.pytorch/lib/dataset/coco.py ,here define how this repo load and pre-process the train/test data

**Comment by DonaldKam** [comment]
@HuangJunJie2017 Thank you twice but you don't really answer my questions. I am using **mpii** dataset. **MPII** instead of **COCO**！ Why is it a single value in **annot\train.json** (**mpii**)？How is it computed?  It is 2-tuple in COCO.
![image](https://user-images.githubusercontent.com/44252954/89757838-f8e9ee80-db18-11ea-9b2d-611b4dbd4424.png)

**Comment by HuangJunJie2017** [comment]
@DonaldKam mpii is different from coco, and you can refer to https://github.com/HuangJunJie2017/UDP-Pose/blob/master/deep-high-resolution-net.pytorch/lib/dataset/mpii.py for data loading and pre-processing, in line 56 :s = np.array([a['scale'], a['scale']], dtype=np.float) , here single value scale in annotation is conver to 2-tuple
